# SPDX-License-Identifier: Apache-2.0

[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "Unicode-3.0",
]
private = { ignore = true }

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/PLeVasseur/up-rust.git"]
required-git-spec = "rev"
